### PR TITLE
Only show "resend" for completed orders

### PR DESCRIPTION
**Pull request by jordan-brough**
It seems like it makes sense to only "resend" if it's been sent previously.

And it seems reasonable for customized email templates to expect to be given
completed orders (like ours does).  We got an error when an admin accidentally
clicked "resend" on an incomplete order.

### CODE REVIEW

**Comment by jordan-brough** [comment]
Lmk if someone knows of valid use case for "resending" order confirmation emails on incomplete orders.

**Comment by athal7** [comment]
:+1:

**Comment by gmacdougall** [comment]
Any reason to include the logic here, and not within the cancan ability?

**Comment by jordan-brough** [comment]
Seems like a good idea to me. I'll update to that.

**Comment by athal7** [comment]
@jordan-brough all good?

**Comment by jordan-brough** [comment]
I keep meaning to get back to this.

@gmacdougall whenever I think of getting back to the cancan part I hesitate because I don't see other examples of us using cancan like that (maybe I'm missing them?). It feels a little off to me to mix something like order state with user authorization.  Does that seem strange to you?

**Comment by gmacdougall** [comment]
Yeah, I can see the argument for that. I'm fine with that solution if everyone else is.

**Comment by athal7** [comment]
:+1:

**Pull request merged**
