### PR TITLE
Remove spree_orders/considered_risky

### PR DESCRIPTION
**Pull request by athal7**

### CODE REVIEW

**Comment by athal7** [comment]
contains work from https://github.com/bonobos/spree/pull/284

**Comment by cbrunsdon** [comment]
:+1: because I don't expect order.is_risky? to be too hard to support in whatever system we eventually have.

**Comment by athal7** [comment]
looking for a Bonobos approval here as well. @magnusvk @jordan-brough

**Comment by jordan-brough** [comment]
Nice, so it wasn't even actually being used in Spree?  :+1: 

It looks like the "considered risky" stuff in here is also obsolete? https://github.com/bonobos/spree/blob/0667fcd97547bf318e139d1c5f61181de1ac0444/backend/app/assets/stylesheets/spree/backend/globals/_variables.scss
Shall we go ahead and clean that stuff out as well?

**Comment by gmacdougall** [comment]
Spree's fraud flow/risk related stuff is generally incomplete. It doesn't do anything that reasonably works out of the box, and can't be customized without a significant effort.

It's something I'd like to target for improvement.

**Comment by athal7** [comment]
@gmacdougall so is that a :+1: or a :-1: on this?

**Comment by gmacdougall** [comment]
:+1: It deletes bad code that doesn't work right. My favourite kind of commit!

**Comment by athal7** [comment]
cedfb83

**Comment by athal7** [comment]
@jordan-brough i'm going to look at the css removal separately (forgot here)

**Pull request closed without merging**
