### PR TITLE
Add acts_as_paranoid to stock transfer and transfer items

### PR DESCRIPTION
**Pull request by richardnuno**

### CODE REVIEW

**Comment by athal7** [comment]
:+1:

**Comment by gmacdougall** [comment]
Can you please give a description as to why this is a desired change?

**Comment by richardnuno** [comment]
@gmacdougall It'd make it easier to recover data if we allow stock transfer deletion (which we hope to in the near future) in the admin UI.

**Comment by jhawthorn** [comment]
I'm lukewarm on this. I don't like seeing `acts_as_paranoid` added especially when it's not currently being used.

I question what the semantics of "deleting" a stock transfer are. Should it undo a transfer that has happened? Will a deleted transfer ever be visible in the admin? Can transfer items ever be deleted without their parent transfer (and what does that mean)?

I'd probably prefer adding a `cancelled_at` field, if that's what's being modelled here.

That said, it looks correct if using paranoia is desired.

**Comment by gmacdougall** [comment]
I agree with @jhawthorn here. I'm scared of deleting a stock transfer in this manner.

**Comment by richardnuno** [comment]
Apologies but I forgot to include a very important part of this change. We would only want to allow a user to destroy a stock transfer that has not been finalized. I've added a guard to that effect that wasn't in the initial code.

@jhawthorn to answer your questions, the intention is that the deleted stock transfers wouldn't be displayed in the UI. It would basically allow a user to "undo" a mistakenly created stock transfer, but only if it hadn't been finalized. There is already a guard that prevents transfer items from being destroyed if the stock transfer is finalized. Since a stock transfer that has been finalized can't be destroyed, there's no need to undo the transferred stock.

@jhawthorn @gmacdougall does this change seem more reasonable now?

**Comment by gmacdougall** [comment]
I'm still concerned about this. Under what circumstance does a transfer get finalized?

I would not want a stock transfer to be deleted if it has taken any action on the underlying item inventory. If a stock transfer has caused an item to be added somewhere, or removed from somewhere. I would not want it to be deleted. I don't believe that finalized represents that logic.

I don't think `acts_as_paranoid` is right for this. If the thing was created as a mistake, I'd want to be able to undo the changes that it made, and clean up the record. At that point, I want the record and its transfer items to be deleted.

My concern is that this doesn't solve the problem at hand.

**Comment by richardnuno** [comment]
A stock transfer is finalized when a user has finished adding all of the transfer items they want to be part of the stock transfer. Finalizing the stock transfer will basically "freeze" it in terms of what transfer items it will have associated with it.

When an admin has marked a  stock transfer as finalized, that stock transfer can then be marked as shipped. The stock items will only be un-stocked after the stock transfer has been marked as shipped.

To clarify, the intention is not to "rollback" a deleted stock transfer. I agree that once stock movements have been made, recovering data would be a much more involved task but the guard to prevent deleting finalized stock transfers should prevent that from happening.

The intention is to (in the near future) allow users to delete stock transfers that may get created by accident or as a test for example and not have those clutter the index page. We'd like to add the `acts_as_paranoid` just as a safety net in case someone accidentally deletes a stock transfer they've been building and haven't finalized yet so that we can quickly recover that data.

**Comment by gmacdougall** [comment]
Thanks for the follow up on this @richardnuno. I really appreciate the thought you've put in to it.

I'm glad that we share the same concerns about the can of worms of undoing a stock transfer. I was very concerned at first about the details involved here.

Should there also be a validation on `TransferItem` that it can not be destroyed if the `StockTransfer` has been finalized?

**Comment by richardnuno** [comment]
@gmacdougall no problem! That validation already exists: https://github.com/bonobos/spree/blob/2-2-dev/core/app/models/spree/transfer_item.rb#L16

**Comment by gmacdougall** [comment]
Perfect. :+1:

**Comment by allisonlarson** [comment]
:+1:

**Pull request merged**
