### PR TITLE
Prevent inventory unit deletion when return items are present

### PR DESCRIPTION
**Pull request by magnusvk**
Instead of automatically deleting associated return items let's
prevent deletions until we understand what a valid scenario for that
might be.

This reverts part of commit 649fb4a48fa3714e401cc51c7f13fe0aa53cb223.

### CODE REVIEW

**Comment by magnusvk** [comment]
Code by @jordan-brough originally; we are both :+1: on this.

This partially rolls back #321 as we think that inventory units still associated with return items never should be deleted.

@cbrunsdon @jhawthorn @gmacdougall would love your input on this

**Comment by jordan-brough** [comment]
Thanks @magnusvk.

**Comment by gmacdougall** [comment]
Makes sense to me. Why were the inventory units being deleted out of curiousity?

**Comment by jordan-brough** [comment]
We're not sure -- we're doing this so that we get an error report when it happens.

**Comment by cbrunsdon** [comment]
If we're just doing this to debug whats happening, shouldn't that go in your app?

**Comment by magnusvk** [comment]
@cbrunsdon: I'd put it differently: From our understanding of the data and domain model, we believe that inventory units still attached to a return item should not be deleted. Any instance where they would be we would consider a bug (pending new information).

Given that, the more correct course of action here is to raise an exception rather than just silently propagating the destroy.

**Comment by jordan-brough** [comment]
yeah, what magnus said

**Comment by magnusvk** [comment]
@cbrunsdon Given the extra context, are we ok to merge this?

**Comment by cbrunsdon** [comment]
:+1:

**Pull request merged**
