### PR TITLE
Speed up specs by 9.5 minutes

### PR DESCRIPTION
**Pull request by jordan-brough**
I went looking for some low-hanging fruit to speed up specs.  I found some. 

All these times are on my own computer.

Overall: 9.5min speedup (when run serially)

Core (7.5min speedup)
  - Before: 762s
  - After:  306s

Backend (92s speedup)
  - Before: 473s
  - After:  381s

API (26s speedup)
  - Before: 93s
  - After:  67s

Frontend (no change)
  - Before: 123s
  - After:  121s

### CODE REVIEW

**Comment by philbirt** [comment]
:shipit:

**Comment by jordan-brough** [comment]
Speedup on CircleCI was about 9 minutes:

screenshot-2015-04-10-08-47-34

(most recent time is this one)

**Comment by jordan-brough** [comment]
cc @jhawthorn @cbrunsdon @gmacdougall @athal7 @magnusvk

**Comment by athal7** [comment]
:+1: I'd be interested to try to make the line_item_count=1 by default at some point. This is a great step towards that.

**Comment by jordan-brough** [comment]
@athal This actually does do that. :)  You mean [this](https://github.com/bonobos/spree/pull/327/files#diff-b88375f378b6372af0d19d209f45d104L24) right?  There were a couple places where I still explicitly specified it as 1 since it seemed like the spec specifically expected 1 line item to be present.

**Comment by athal7** [comment]
ah yes i must have glazed over that.

**Comment by cbrunsdon** [comment]
Ha, excellent. This was on my "todo" list for solidusconf.

:+1:

**Pull request merged**
