### PR TITLE
Trigger off of order#is_risky? instead of order#consider_risk? for risk box in admin.

### PR DESCRIPTION
**Pull request by athal7**
is_risky is a better check, and is what is used inside of the included
partial anyways.

### CODE REVIEW

**Comment by athal7** [comment]
relates to https://github.com/bonobos/spree_signifyd/pull/24

**Comment by gmacdougall** [comment]
We should consider renaming one of these methods. This is very confusing as is.

Renaming `is_risky?` to `has_risky_payments?` would make this a bit less confusing and more descriptive of what's actually happening.

**Comment by athal7** [comment]
@gmacdougall i agree these are confusing. i think has_risky_payments is a bit too specific though. it seems to me that payments are just an implementation detail, that we happen to be determining risk based off of payments because that is the best we have available. when hooked up to a system like signifyd, i would want to not check payments to determine risk, but rather defer to their determination of risk.

all this leads me to want to make a change to considered_risky rather than is_risky, but it also makes me question what the point of considered_risky is after all. everything that I can find seems to indicate that considered_risky is simply a denormalization of the time when risk was last calculated, which makes me want to just remove the considered_risky column entirely and evaluate risk on the fly as needed.

**Comment by gmacdougall** [comment]
We can probable just merge this for now. Risky payments & fraud flow is something that needs to be addressed in a better fashion than what we currently do.

**Comment by athal7** [comment]
i'll submit a separate PR to remove considered_risky. it is used in surprisingly few places and is quite unhelpful.

**Comment by athal7** [comment]
39e556d

**Pull request closed without merging**
