### PR TITLE
remove reference to shipment.adjustment

### PR DESCRIPTION
**Pull request by jordan-brough**
Cherry-pick commit from @cbrunsdon and add some extra removal also.  I noticed this broken code while looking at some shipping stuff and found Clarke's commit removing it.

### CODE REVIEW

**Comment by philbirt** [comment]
yay for deleting code :+1:

**Comment by jordan-brough** [comment]
I don't know why CircleCI isn't running specs on the additional commit but the specs pass locally for me so I'm going to merge.

**Comment by jordan-brough** [comment]
Oops, I forgot I should wait for a FRT thumbsup.  Any concerns w/ this @cbrunsdon @jhawthorn @gmacdougall?

**Comment by gmacdougall** [comment]
Shouldn't be a problem.

:+1: to pretty much anything that removes code that isn't used or doesn't work.

**Pull request merged**
