### PR TITLE
Cherry pick some commits from 2-2-stable

### PR DESCRIPTION
**Pull request by jordan-brough**
Two things related to order-updating. These are helpful for the current order update effort and they get us closer to the spree/spree 2-2-stable and master branches as well.

### CODE REVIEW

**Comment by athal7** [comment]
looks good to me

**Comment by jordan-brough** [comment]
@athal7 I rebased on 2-2-dev and force-pushed. Should CircleCI kick in automatically?

**Comment by athal7** [comment]
Yes that's what I would expect. The sha changed right?

**Comment by athal7** [comment]
Ah I wonder if it doesn't run since its on your fork.

**Comment by jordan-brough** [comment]
@athal7 I opened a second PR w/ a bonobos base and that PR did kick off circleci. I'll try again w/ a different fresh PR based off my own fork and see if it still doesn't work.  If it doesn't is there a way to fix that w/ circleci? (I assume yes because spree seems to do it?)

**Comment by athal7** [comment]
@jordan-brough looks like you are all set with circle-ci things ?

**Pull request merged**
