### PR TITLE
Use Spree.ajax for Spree api ajax requests.

### PR DESCRIPTION
**Pull request by athal7**
Rather than setting it as the default for ajax requests, so that we don't send the api key to remote services.

### CODE REVIEW

**Comment by athal7** [comment]
went with headers instead of param here not for any strong reason, just felt a bit cleaner than messing with query params and/or data hashes.

**Comment by magnusvk** [comment]
This looks good, though I don't know how we verify that we've caught every instance. I assume you ack'ed your way through?

Also: Would it make more sense to create some function that wraps `$.ajax` and auto-adds the API key as a header? That would seem cleaner to me but there may be a reason not to do it.

**Comment by athal7** [comment]
yep ack-ing and manual testing, it's possible we'll come across something, i'll monitor 401s after deploy.

yea i think that would work well, iirc we had some security concerns, but now that i think about it we decided that once they have JS on the page then it's not a big difference. i'll try that out

**Comment by athal7** [comment]
@magnusvk fun story, Spree.ajax already exists and works as we desire. I still added the headers to the select2 ajax requests since it appears necessary there.

**Comment by magnusvk** [comment]
This is good, though I'd like it even better if `Spree.ajax` used a header rather than a query param for this.

**Comment by magnusvk** [comment]
:+1:

**Comment by athal7** [comment]
@magnusvk mind taking another look?

**Comment by magnusvk** [comment]
Looks good to me visually. :+1: Do we need FRT to look at this potentially?

**Comment by athal7** [comment]
@gmacdougall @cbrunsdon @jhawthorn care to take a look?

**Comment by gmacdougall** [comment]
:+1:

**Comment by athal7** [comment]
one step further i think would be great to take is to not store the api key in the dom. maybe in a path-restricted secure cookie? i'll save that for a later change though.

**Pull request merged**
