### PR TITLE
Remove link_by_email before_create hook on order

### PR DESCRIPTION
**Pull request by athal7**
seems unnecessary now that we have the explicit associate_user

### CODE REVIEW

**Comment by athal7** [comment]
seems unnecessary now that we have the explicit associate_user, we'll see if the specs pass :)

**Comment by athal7** [comment]
ping @jordan-brough

**Comment by jordan-brough** [comment]
:eyes:

**Comment by jordan-brough** [comment]
I'm not 100% sure on this, but it seems like [this code](https://github.com/bonobos/spree/blob/4b2909f/core/lib/spree/core/controller_helpers/order.rb#L31-L35) might still be requiring the removed code?  It seems to be called (at least) by frontend [here in Spree::OrdersController#populate](https://github.com/bonobos/spree/blob/4b2909f/core/lib/spree/core/controller_helpers/order.rb#L31-L35).

**Comment by athal7** [comment]
i think you are right, maybe this is a bit premature, i'll close for now

**Pull request closed without merging**
