### PR TITLE
Fix for order payment state when total is zero

### PR DESCRIPTION
**Pull request by jordan-brough**
The presence of "invalid" payments were causing a $0 order to have
payment_state=failed.

This code and the associated specs definitely need some improvement.
This is not the ideal fix but it is the least invasive solution I
could come up with for a real problem we're seeing.

cc @philbirt

### CODE REVIEW

**Comment by jordan-brough** [comment]
Note: If anyone has time to craft a deeper and more robust fix for this I would be very much in favor of that!

**Comment by gmacdougall** [comment]
Just trying to visualize the problem here.

A $0 order had a payment, but that payment was not valid so the order payment state was set to failed. Instead, the order will be set to paid since it now fails that check, and has no outstanding balance.

The more invasive, but better, solution would probably be to ensure that no payments are created for a $0 order since they are not required.

**Comment by jordan-brough** [comment]
@gmacdougall yeah that would be great though with the way that "invalid" (as opposed to "failed") payments work it seems like that might be pretty tough.  I'm thinking we should merge this part in either way (handle the data regardless of how it got there).  Do you agree?

e.g. if you take your order all the way to the "confirm" state and then add a promo that lowers the total to $0, you'd already have some "invalid" (not "failed") payments that stick around forever wouldn't you?

**Comment by gmacdougall** [comment]
Yeah, I think this is better than what we've got.

:+1:

**Comment by jordan-brough** [comment]
@magnusvk @athal7 @cbrunsdon @jhawthorn I need a second thumb here if one of you has a minute.

**Comment by magnusvk** [comment]
:+1: agree with your discussion.

**Pull request closed without merging**
