### PR TITLE
Add updated_at to country json

### PR DESCRIPTION
**Pull request by kamui**
This adds the `updated_at` column to the country serializer.

### CODE REVIEW

**Comment by gmacdougall** [comment]
This looks like it will work. However, I don't know why we need this. Could you please add a bit more to the description?

**Comment by kamui** [comment]
We're using the API call to get a list of states to populate the billing/shipping dropdown at checkout. Since this data changes very infrequently,we plan on caching this API response. We'd like to use the `updated_at` value as part of an autoexpiring cache key.

**Comment by gmacdougall** [comment]
I would tend to side with this being something configured within your specific customization of Spree rather than in the core repository.

**Comment by kamui** [comment]
We could move this there. Just curious why you think that would be better. Putting the updated_at timestamp in the response seems like it would be something that could be useful to most people using an API endpoint.

**Comment by gmacdougall** [comment]
No specific reason. I just don't generally foresee a need for this. Updating countries is quite rare, and I can't think of a scenario where I'd want to know when a particular country was most recently updated.

Can you please explain your caching strategy a bit more and why it's important? I imagine that something else is touching country and that's what the cache key is being used for.

**Comment by kamui** [comment]
Nothing else is touching country, but our goal is to have our front end app (in the backend) retrieve the list of states and cache that so we don't need to make that request per checkout page load. We'd like some way to cache that information without having to hash the entire response and having updated_at would make a good proxy to determine whether the country/state information has changed.

**Comment by cbrunsdon** [comment]
Makes sense to me, :+1:

**Comment by athal7** [comment]
@kamui just checking in on the status here

**Comment by kamui** [comment]
We thought of another way to expire this cache based on the Etag of the response, so we don't need the `updated_at` field.

**Pull request closed without merging**
