### PR TITLE
Set StateMachine::Maching.ignore_method_conflicts in initializer 

### PR DESCRIPTION
**Pull request by jhawthorn**

### CODE REVIEW

**Comment by Senjai** [comment]
:+1:

**Comment by jordan-brough** [comment]
@jhawthorn you mentioned the initializer possibly not running early enough.  It does seem like these initializers have a good chance of running too late.  We could also try to hook in even earlier in core/engine.rb.  But what about just adding `StateMachine::Machine.ignore_method_conflicts = true` right [here](https://github.com/bonobos/spree/blob/e7d8150c913a5a38a8475b709a772db0b92c7755/core/lib/spree/core/environment.rb#L5) at the class-definition level?  At that point Spree::Payment can't even have been defined yet so we're guaranteed that it's early enough.  It's hacky, but all of this is hacky until we get the better solution of removing it entirely, like you said.

**Comment by jordan-brough** [comment]
Btw, I noticed that this fix affects Adjustment#open as well, since Adjustment#open overwrites Kernel#open.  E.g. in our app if we try to call adjustment.open we get:

```
>> Spree::Adjustment.first.open
NoMethodError: private method `open' called for #<Spree::Adjustment:0x007f890c739d20>
>> Spree::Adjustment.instance_method(:open)
=> #<UnboundMethod: Spree::Adjustment(Kernel)#open>
```

i.e. [this](https://github.com/pluginaweek/state_machine/blob/8a3ba81801782ac4ef9d4ace1209d8d50ffccdb0/lib/state_machine/machine.rb#L348-L357).  So if we do remove `StateMachine::Machine.ignore_method_conflicts` eventually then Adjustment#open will remain unavailable unless we explicitly define it or rename it.

**Comment by jhawthorn** [comment]
I would prefer putting it in `lib/spree/core/engine.rb` over `lib/spree/core/environment.rb` (as I don't believe environment has anything to do with state machines).

We discussed alternatives in slack to eventually move to, we liked `canceled` instead of `invalid` for payments. Any thoughts on a better naming than `open`/`closed` on adjustments?

**Comment by jordan-brough** [comment]
> I would prefer putting it in lib/spree/core/engine.rb over lib/spree/core/environment.rb

Sure. How about we put it in engine.rb but at the class definition level and not inside an actual initializer?  That should be equally safe but in a nicer spot.

> Any thoughts on a better naming than open/closed on adjustments?

I say if we're going to expend any energy there let's just remove statemachine on Adjustment and move from a `state` string column to a `closed` boolean column.  There are only two states, they can both transition to each other, and there's nothing in Spree itself that uses the statemachine transitions and we don't really want to expose that as an external api anyway.

**Comment by jhawthorn** [comment]
> Sure. How about we put it in engine.rb but at the class definition level and not inside an actual initializer? That should be equally safe but in a nicer spot.

Uh, I know we just agreed on `engine.rb`, but it looked out of place once I put it there. How's here in `lib/spree/core.rb`. I think this "feels" best as it's just after we've required state_machine.



> I say if we're going to expend any energy there let's just remove statemachine on Adjustment and move from a state string column to a closed boolean column. There are only two states, they can both transition to each other, and there's nothing in Spree itself that uses the statemachine transitions and we don't really want to expose that as an external api anyway.

Sounds perfect.

**Comment by jordan-brough** [comment]
:+1: great!

**Comment by cbrunsdon** [comment]
:+1:

**Pull request closed without merging**
