### PR TITLE
Add API feature specs

### PR DESCRIPTION
**Pull request by athal7**
Add some API feature specs to help us feel more comfortable with
changing things under the hood.

A few interesting discoveries around applying promotion codes and
payments through api/orders#create and api/orders#update came out of
this exercise (see comments in the specs).

### CODE REVIEW

**Comment by jordan-brough** [comment]
Wow, this is beautiful.  Really nice levels of abstraction, lots of excellent assertions, code is well-reused between specs, and very readable.  This code makes me happy. :)

The failing jenkins specs are behaving a bit strangely for me, going to take a look a bit later because I'm curious (unless you find out something first).

**Comment by athal7** [comment]
thanks!! i'm looking as well. it does fail for me locally now, though it was passing when i committed it :(

**Comment by athal7** [comment]
apparently the shipment it's applying is now $0, whereas before it was $10

**Comment by athal7** [comment]
@jordan-brough should be all good now

**Comment by jordan-brough** [comment]
@athal7 nice.

fyi I think #225 should fix the underlying issue (and #224 should fix the erratic spec behavior) so you could theoretically revert that last commit, but it seems like the change you made makes the spec more robust and makes things more obvious in this spec anyway so :+1: as-is.

**Comment by athal7** [comment]
4b2909f

**Pull request closed without merging**
