### PR TITLE
Use OrderContents in admin/orders/edit|cart and admin/customer/update

### PR DESCRIPTION
**Pull request by jordan-brough**

### CODE REVIEW

**Comment by gmacdougall** [comment]
I think this would be an appropriate time to bring the code over from:

https://github.com/bonobos/spree/blob/71f4c1d6f1cec2a325a5b102bed53bcd03d859b9/core/app/models/spree/order.rb#L460-L462

The order is just doing:

```Ruby
    def refresh_shipment_rates
      shipments.map &:refresh_rates
    end
```

I also think the expectation on `Spree::Stock::Estimator` is going too deep in to the implementation details of other classes.

I would want the order contents spec to expect that `refresh_rates` was called on each of the shipments for the order and leave the other testing for a higher level.

**Comment by jordan-brough** [comment]
> I think this would be an appropriate time to bring the code over

Great point. I've added that change. Thanks!

**Comment by jordan-brough** [comment]
> I also think the expectation on Spree::Stock::Estimator is going too deep in to the implementation details of other classes.
>
> I would want the order contents spec to expect that refresh_rates was called on each of the shipments for the order and leave the other testing for a higher level.

Yeah, I agree that the Estimator stubbing here is non-ideal.  Though I do think it's worthwhile to actually have that 'higher level' kind of testing in these specs, even if we also have further coverage elsewhere.  i.e. keep the order interface unit specs more in the classic style than the mockist style. Ideally I'd like to see something like this:

```ruby
it 'updates shipping rates' do
  new_shipping_method = add_new_qualifying_shipping_method
  order.contents.refresh_rates
  expect(shipment.shipping_methods).to include(new_shipping_method)
end
```

Rather than stubbing the shipment-refresh calls.  I can take another pass at doing that w/o the Estimator stubbing. I think these particular specs (the specs for the interface used to mutate orders) are a great place to focus on integrated specs rather than isolated specs. Seem reasonable?

**Comment by jordan-brough** [comment]
@gmacdougall I updated to remove the Stock::Estimator expectation.  Good?

**Comment by gmacdougall** [comment]
:+1:

**Comment by jordan-brough** [comment]
Holding off on merging this because it seems like it may have somehow made these two specs fail sporadically:

```
rspec ./spec/features/admin/orders/line_items_spec.rb:36 # Order Line Items can delete a line item
rspec ./spec/features/admin/orders/listing_spec.rb:19 # Orders Listing listing orders should list existing orders
```
I'm going to see if other PRs trigger these failures and maybe take a closer look later.

**Comment by jordan-brough** [comment]
My flaky-spec testing hasn't found anything super definitive and I've seen the same spec failures in at least one other unrelated PR (https://circleci.com/gh/bonobos/spree/390 from PR 260 has the same two failures as https://circleci.com/gh/bonobos/spree/262 from this PR).  I'm going to go ahead and get this merged.

**Pull request closed without merging**
