### PR TITLE
Stop making routes terribly in resource controller

### PR DESCRIPTION
**Pull request by cbrunsdon**
I should have fixed this years ago. Years and years ago. Its right in
other places in this controller. Just not for these two.

Now you can make spree admin controllers to manage other namespaces
objects and it will actually work with the resource controller.

### CODE REVIEW

**Comment by athal7** [comment]
:+1: aside from the failed specs

**Comment by jordan-brough** [comment]
:+1:, ditto on specs.

**Comment by gmacdougall** [comment]
:+1: now that specs are passing

**Comment by cbrunsdon** [comment]
Warning to people: We have had code in our sites that were relying on the broken behaviour (routing to places where we manually mangled routes to make it work).

I still think we should merge this, as IMO its now "correct", but will likely break people stuff.

Maybe I should catch the route error and put a good error message or something?

**Comment by jordan-brough** [comment]
@cbrunsdon I'm not following the breakage issue. Could you give a quick example of how this might break existing code?

**Comment by cbrunsdon** [comment]
we for instance, had a model called VehicleData, it wanted to properly route to the vehicle_datum (using the rails inflections), but the routes and controllers were all set up to route to vehicle_data.

Our controller was technically named wrong, but we didn't notice because of how the previous link_to_edit and resource routes were working.

**Comment by magnusvk** [comment]
@cbrunsdon @jordan-brough Should we be merging this? Sounds like we got thumbs-ups all around?

**Comment by jordan-brough** [comment]
:+1:

**Comment by athal7** [comment]
@cbrunsdon what do you think about if we point this at solidus?

**Comment by magnusvk** [comment]
Submitted against solidus in [solidus#100](https://github.com/solidusio/solidus/pull/100). Going to close this out.

**Pull request closed without merging**
