### PR TITLE
Fix for Calculator factory

### PR DESCRIPTION
**Pull request by jordan-brough**
Using `after(:create)` resulted in the code not applying when 'build' mode was used, as it was being used in this code:

```ruby
factory :shipping_method, class: Spree::ShippingMethod do
  association(:calculator, factory: :calculator, strategy: :build)
end

```

### CODE REVIEW

**Comment by jordan-brough** [comment]
I believe the failing specs are unrelated flaky specs. They pass for me locally.

**Comment by jordan-brough** [comment]
Is there a way to tell circleci to retry the specs for this PR?

**Comment by athal7** [comment]
@jordan-brough yep! if you click through to details, there should be a 'rebuild' button in the top right?

**Comment by jordan-brough** [comment]
@athal7 Hm, perhaps I'd have to be signed in or something...?  Attached is what I see.  (I looked at signing up once but didn't really want to give out access to all my private repos.)  Do we have a common login or anything, if that's the issue?

**Comment by jordan-brough** [comment]
screenshot-2015-02-10-11-36-31

**Comment by jordan-brough** [comment]
Now i'm repro'ing so it looks like it really is my fault

**Comment by jordan-brough** [comment]
@athal7 the specs are now passing. look good?

**Comment by athal7** [comment]
:white_check_mark:

**Pull request closed without merging**
