### PR TITLE
Memoize api user load to better support alternative authentication strategies.

### PR DESCRIPTION
**Pull request by athal7**

### CODE REVIEW

**Comment by magnusvk** [comment]
This will work. A question, though: Would it be better to partially revert [this commit](https://github.com/bonobos/spree/commit/24cc4cadce9fbb7e184487a52106bc02810bba31) by pulling this back into the `authenticate_user` method? This feels like double-`||` this.

Thanks for this.

**Comment by gmacdougall** [comment]
I like Magnus' suggestion.

**Comment by athal7** [comment]
ok i'll give a go

**Comment by athal7** [comment]
@magnusvk @gmacdougall mind taking another look?

**Comment by magnusvk** [comment]
I was thinking something more like #275, though at this point I wonder if your first commit wasn't the best approach. So, I think I just want to leave this up to you now.

**Comment by gmacdougall** [comment]
I'd probably prefer to keep `load_user` in order to maintain code API compatibility.

**Comment by athal7** [comment]
@magnusvk @gmacdougall updated

**Comment by magnusvk** [comment]
:+1:

**Comment by athal7** [comment]
38f7a19

**Pull request closed without merging**
